import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import styles from "../styles/Home.module.css";

export default function Home() {
  const router = useRouter();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <button
        style={{ padding: "8px", height: "40px", background: "blue" }}
        onClick={() => router.push("/ssr-with-bot-detect")}
      >
        To ssr
      </button>
    </div>
  );
}
